In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import joblib
import csv

In [2]:
csvfile = '../Resources/Callstreet_Bets.csv'
data = pd.read_csv(csvfile)
data = data.fillna(0)
data.head()

Date ticker  mention_count  percent_change
0  2021-01-28    AMC          214.0             0.0
1  2021-01-28     BB          123.0             0.0
2  2021-01-28    CLF            0.0             0.0
3  2021-01-28   CLNE            0.0             0.0
4  2021-01-28   CLOV            1.0             0.0

In [3]:
X = data['mention_count'].values.reshape(-1, 1)
y = data['percent_change'].values.reshape(-1, 1)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=32, test_size=0.33)
x_train

array([[0.000e+00],
       [1.000e+00],
       [2.000e+01],
       [0.000e+00],
       [1.000e+00],
       [0.000e+00],
       [2.000e+00],
       [4.400e+01],
       [1.200e+01],
       [0.000e+00],
       [4.300e+01],
       [3.000e+00],
       [1.100e+01],
       [1.300e+01],
       [2.000e+00],
       [1.000e+00],
       [0.000e+00],
       [2.000e+00],
       [2.700e+01],
       [7.000e+00],
       [0.000e+00],
       [1.700e+01],
       [5.000e+00],
       [1.000e+00],
       [2.000e+00],
       [2.000e+00],
       [1.000e+01],
       [0.000e+00],
       [3.400e+01],
       [0.000e+00],
       [2.400e+01],
       [1.300e+01],
       [1.200e+01],
       [2.000e+00],
       [8.000e+00],
       [1.100e+01],
       [0.000e+00],
       [1.500e+01],
       [6.000e+00],
       [6.000e+00],
       [0.000e+00],
       [0.000e+00],
       [9.000e+00],
       [0.000e+00],
       [0.000e+00],
       [1.000e+01],
       [0.000e+00],
       [0.000e+00],
       [0.000e+00],
       [1.330e+02],


In [5]:
x_test

array([[0.000e+00],
       [0.000e+00],
       [3.000e+00],
       [0.000e+00],
       [4.100e+01],
       [4.000e+00],
       [0.000e+00],
       [3.000e+00],
       [1.400e+01],
       [0.000e+00],
       [2.000e+01],
       [4.000e+00],
       [2.000e+00],
       [9.000e+00],
       [0.000e+00],
       [0.000e+00],
       [0.000e+00],
       [8.000e+00],
       [1.000e+00],
       [4.000e+00],
       [0.000e+00],
       [2.000e+00],
       [0.000e+00],
       [1.000e+00],
       [1.000e+01],
       [1.400e+01],
       [1.000e+00],
       [2.000e+00],
       [2.700e+01],
       [4.000e+00],
       [0.000e+00],
       [0.000e+00],
       [0.000e+00],
       [1.920e+02],
       [9.000e+00],
       [6.000e+00],
       [7.000e+00],
       [3.300e+01],
       [1.500e+01],
       [2.000e+00],
       [2.000e+00],
       [0.000e+00],
       [0.000e+00],
       [0.000e+00],
       [0.000e+00],
       [1.000e+00],
       [0.000e+00],
       [0.000e+00],
       [1.000e+00],
       [1.280e+03],


In [6]:
y_train

array([[-4.04852872e-02],
       [-2.41588427e-02],
       [ 1.16686768e-02],
       [ 6.67709738e-02],
       [ 1.54051459e-02],
       [ 2.05171659e-02],
       [-3.13163805e-02],
       [-1.50791068e-02],
       [ 1.06849593e-02],
       [-3.04410390e-02],
       [-1.21353839e-01],
       [-2.35305872e-02],
       [ 0.00000000e+00],
       [ 3.10987083e-02],
       [ 1.02041602e-02],
       [ 4.71142929e-03],
       [-2.06694372e-02],
       [ 8.78613853e-02],
       [-5.00887429e-02],
       [-3.63676712e-02],
       [ 1.61293664e-02],
       [-3.66300440e-03],
       [ 4.82021269e-02],
       [ 1.78804280e-02],
       [ 5.33878967e-02],
       [-2.58251183e-02],
       [-2.40975285e-02],
       [-1.11112151e-02],
       [-3.10179413e-02],
       [-9.56320558e-02],
       [ 0.00000000e+00],
       [ 4.65968739e-02],
       [-3.47373014e-03],
       [ 2.71861151e-02],
       [-1.46038381e-02],
       [-6.16172116e-02],
       [-2.06271952e-02],
       [-1.42182353e-02],
       [ 4.8

In [7]:
y_test

array([[-3.03140568e-02],
       [-1.42213089e-02],
       [-6.78660529e-02],
       [-9.47876721e-03],
       [-1.35518602e-02],
       [ 8.53676354e-02],
       [-1.58636776e-02],
       [-2.31208240e-03],
       [ 7.96176790e-02],
       [-4.87900993e-02],
       [ 5.70768324e-02],
       [-9.10354740e-02],
       [-1.69783200e-02],
       [-1.31917216e-02],
       [ 1.53662204e-02],
       [-3.27642479e-02],
       [-4.44553416e-04],
       [-8.45573897e-02],
       [ 3.17487828e-02],
       [-1.70686951e-02],
       [-2.32089372e-02],
       [ 2.20893868e-01],
       [ 1.94632027e-02],
       [ 1.36058522e-01],
       [-2.34615345e-02],
       [-7.08953831e-04],
       [-3.60152693e-03],
       [ 1.65292857e-02],
       [-2.37854769e-02],
       [ 2.65110770e-02],
       [ 0.00000000e+00],
       [ 6.40935382e-02],
       [ 9.33692339e-02],
       [ 3.92789056e-02],
       [ 6.10689764e-02],
       [-2.65758552e-02],
       [ 1.07587195e-03],
       [-4.04410052e-02],
       [-5.8

In [8]:
tree_regressor = DecisionTreeRegressor()
model = tree_regressor.fit(x_train,y_train)

In [9]:
model.score(x_test, y_test)

-0.2973738815036619

In [10]:
model.score(x_train, y_train)

0.45435269509638937

In [11]:
filename = "model.sav"
joblib.dump(model, filename)

['model.sav']

In [12]:
loaded_model = joblib.load(filename)

In [13]:
loaded_model.predict([[700]])

array([0.02642557])